[build]
publish = "public"
functions = "functions"
command = "make build"

[build.environment]
# Change this path with the path to your repository
GO_IMPORT_PATH = "github.com/smoya/netlify-functions-2"
